package tokenizer

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type fixture struct {
	Text    string   `json:"text"`
	IDs     []int    `json:"ids"`
	Offsets [][2]int `json:"offsets"`
}

// modelPath is where Task 17's asset fetch puts tokenizer.json. The gate test
// skips when it is absent so `go test ./...` never depends on a download.
func modelPath(t *testing.T) string {
	t.Helper()
	p := os.Getenv("AIPROXY_TOKENIZER_JSON")
	if p == "" {
		t.Skip("set AIPROXY_TOKENIZER_JSON to the model's tokenizer.json to run the gate")
	}
	return p
}

// THE GATE. Exact agreement with the reference on ids and byte offsets, for
// every fixture. Nothing downstream of the tokenizer may be built until this
// passes, because a span that is one byte out redacts the wrong text.
//
// Two fixture files, both generated by scripts/gen-tokenizer-fixtures.py:
// offsets.json is the readable hand-written core, and offsets_extra.json is a
// seeded corpus of randomised and adversarial inputs. The second one is not
// decoration — the first implementation of this package passed every case in
// offsets.json while still disagreeing with the reference on any character
// whose bytes do not merge into a single token, and on literal added tokens.
func TestEncodeMatchesReferenceExactly(t *testing.T) {
	tok, err := Load(modelPath(t))
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	for _, name := range []string{"offsets.json", "offsets_extra.json"} {
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join("testdata", name))
			if err != nil {
				t.Fatalf("fixtures missing; run scripts/gen-tokenizer-fixtures.py: %v", err)
			}
			var fixtures []fixture
			if err := json.Unmarshal(raw, &fixtures); err != nil {
				t.Fatal(err)
			}
			if len(fixtures) == 0 {
				t.Fatal("no fixtures")
			}
			for i, f := range fixtures {
				got, err := tok.Encode(f.Text)
				if err != nil {
					t.Errorf("case %d (%q): Encode: %v", i, trunc(f.Text), err)
					continue
				}
				if len(got) != len(f.IDs) {
					t.Errorf("case %d (%q): %d tokens, reference has %d", i, trunc(f.Text), len(got), len(f.IDs))
					continue
				}
				for j, tk := range got {
					if tk.ID != f.IDs[j] {
						t.Errorf("case %d (%q) token %d: id %d, want %d", i, trunc(f.Text), j, tk.ID, f.IDs[j])
					}
					if tk.Start != f.Offsets[j][0] || tk.End != f.Offsets[j][1] {
						t.Errorf("case %d (%q) token %d: span [%d,%d), want [%d,%d)",
							i, trunc(f.Text), j, tk.Start, tk.End, f.Offsets[j][0], f.Offsets[j][1])
					}
				}
			}
		})
	}
}

// Offsets must tile the input exactly: contiguous, in order, ending at len(text).
// This holds regardless of the fixtures and catches the whole class of bug where
// a decoded token's length is computed wrongly.
func TestOffsetsTileTheInput(t *testing.T) {
	tok, err := Load(modelPath(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, text := range []string{
		"hello world", "héllo 😀 wörld", "  spaced  out  ",
		`{"key":"sk-ant-abcdefghijklmnop"}`, "日本語",
	} {
		got, err := tok.Encode(text)
		if err != nil {
			t.Fatalf("Encode(%q): %v", text, err)
		}
		prev := 0
		for j, tk := range got {
			if tk.Start != prev {
				t.Errorf("%q token %d starts at %d, previous ended at %d", text, j, tk.Start, prev)
			}
			if tk.End < tk.Start || tk.End > len(text) {
				t.Errorf("%q token %d span [%d,%d) is out of range for %d bytes",
					text, j, tk.Start, tk.End, len(text))
			}
			prev = tk.End
		}
		if len(got) > 0 && prev != len(text) {
			t.Errorf("%q: offsets end at %d, want %d", text, prev, len(text))
		}
	}
}

// Spans must cover the input in order and never cut a character in half. This is
// the invariant that actually holds in general, and it is weaker than
// TestOffsetsTileTheInput on purpose: when a character's bytes are split across
// several tokens the reference gives every one of them the whole character's
// range, so consecutive spans repeat rather than tile. A redactor taking
// min(Start)/max(End) over a run of tokens is safe either way.
func TestSpansCoverTheInputAndAlignToCharacters(t *testing.T) {
	tok, err := Load(modelPath(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, text := range []string{
		"hello world", "héllo 😀 wörld", "  spaced  out  ",
		`{"key":"sk-ant-abcdefghijklmnop"}`, "日本語",
		// Characters whose bytes do not merge, so one character becomes several
		// tokens that all report the same span.
		"=﷽V", "ｳB", "∑x", "한 a", "\u0301\u0301\u0301",
		// Added tokens, matched literally and emitted as one token.
		"W <|endoftext|> main", "<|endoftext|><|start|>", "x<|endofprompt|>",
	} {
		got, err := tok.Encode(text)
		if err != nil {
			t.Fatalf("Encode(%q): %v", text, err)
		}
		if len(got) == 0 {
			if text != "" {
				t.Errorf("%q: no tokens", text)
			}
			continue
		}
		covered, prevStart := 0, 0
		for j, tk := range got {
			if tk.Start < prevStart {
				t.Errorf("%q token %d starts at %d, before the previous token's %d", text, j, tk.Start, prevStart)
			}
			if tk.Start > covered {
				t.Errorf("%q token %d starts at %d, leaving bytes [%d,%d) uncovered", text, j, tk.Start, covered, tk.Start)
			}
			if tk.End <= tk.Start || tk.End > len(text) {
				t.Errorf("%q token %d span [%d,%d) is out of range for %d bytes", text, j, tk.Start, tk.End, len(text))
			}
			if !charAligned(text, tk.Start) || !charAligned(text, tk.End) {
				t.Errorf("%q token %d span [%d,%d) cuts a character in half", text, j, tk.Start, tk.End)
			}
			prevStart = tk.Start
			if tk.End > covered {
				covered = tk.End
			}
		}
		if covered != len(text) {
			t.Errorf("%q: spans cover %d bytes, want %d", text, covered, len(text))
		}
	}
}

// charAligned reports whether i is a character boundary in s.
func charAligned(s string, i int) bool {
	if i == 0 || i == len(s) {
		return true
	}
	for j := range s {
		if j == i {
			return true
		}
		if j > i {
			return false
		}
	}
	return false
}

func trunc(s string) string {
	if len(s) > 40 {
		return s[:40] + "..."
	}
	return s
}

// Load must refuse a tokenizer.json whose settings differ from the ones this
// package was verified against, because every one of them changes the offsets or
// the ids without changing anything a fixture can see. The doctored files are the
// real file with exactly one field patched, so the test proves the assertion
// fires rather than proving a hand-built stub is rejected.
func TestLoadRejectsSettingsThatWouldShiftOffsets(t *testing.T) {
	path := modelPath(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	// Sanity check: the real file loads. Otherwise a rejection below might be for
	// the wrong reason.
	if _, err := Load(path); err != nil {
		t.Fatalf("the real file must load: %v", err)
	}

	for _, tc := range []struct {
		name    string
		find    string
		replace string
		wantErr string
	}{{
		name:    "post_processor trim_offsets",
		find:    `"trim_offsets": false`,
		replace: `"trim_offsets": true`,
		wantErr: "trim_offsets=true",
	}, {
		name:    "pre_tokenizer add_prefix_space",
		find:    `"add_prefix_space": false`,
		replace: `"add_prefix_space": true`,
		wantErr: "add_prefix_space=true",
	}, {
		name:    "pre_tokenizer use_regex",
		find:    `"use_regex": false`,
		replace: `"use_regex": true`,
		wantErr: "use_regex=true",
	}, {
		name:    "Split behavior",
		find:    `"behavior": "Isolated"`,
		replace: `"behavior": "Removed"`,
		wantErr: `behavior "Removed"`,
	}, {
		name:    "Split invert",
		find:    `"invert": false`,
		replace: `"invert": true`,
		wantErr: "invert=true",
	}, {
		name:    "model ignore_merges flipped",
		find:    `"ignore_merges": true`,
		replace: `"ignore_merges": false`,
		wantErr: "ignore_merges=false",
	}, {
		// An absent value is not a verified value, so it must be refused rather
		// than defaulted to the reference's own default of false.
		name:    "model ignore_merges absent",
		find:    "\n    \"ignore_merges\": true,",
		replace: "",
		wantErr: "no ignore_merges field",
	}, {
		name:    "normalizer",
		find:    `"normalizer": null`,
		replace: `"normalizer": {"type": "NFKC"}`,
		wantErr: "normalizer",
	}} {
		t.Run(tc.name, func(t *testing.T) {
			// Exactly one occurrence, so the patch is unambiguous. If the file's
			// formatting ever changes this fails loudly instead of silently
			// patching nothing and reporting a pass.
			if n := strings.Count(string(raw), tc.find); n != 1 {
				t.Fatalf("found %q %d times in the real file, want exactly 1", tc.find, n)
			}
			doctored := strings.Replace(string(raw), tc.find, tc.replace, 1)
			p := filepath.Join(t.TempDir(), "tokenizer.json")
			if err := os.WriteFile(p, []byte(doctored), 0o600); err != nil {
				t.Fatal(err)
			}
			_, err := Load(p)
			if err == nil {
				t.Fatalf("Load accepted a file with %s patched to %s; it must refuse settings it was not verified against", tc.find, tc.replace)
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Errorf("error does not name the offending field: got %q, want it to contain %q", err, tc.wantErr)
			}
		})
	}
}

// Malformed UTF-8 has no reference to compare against: the tokenizers library
// takes a Python str, which cannot hold invalid bytes, and a JSON fixture cannot
// carry them either. It still reaches this code, because the proxy forwards
// whatever bytes an agent sends. So it is property-tested instead: Encode must
// not fail, must cover every byte, and must treat each invalid byte as a
// character of its own — which is what Go's own string iteration does, and what
// the offset arithmetic in encodePiece relies on.
func TestEncodeHandlesMalformedUTF8(t *testing.T) {
	tok, err := Load(modelPath(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, text := range []string{
		"\x80",                      // lone continuation byte
		"ok \x80 then",              // lone continuation byte in context
		"\xe6\x97",                  // truncated three-byte sequence
		"日本\xe6\x97",                // truncated sequence after a valid one
		"\xc0\x80",                  // overlong encoding of NUL
		"\xf0\x9f\x98",              // truncated emoji
		"a\xffb",                    // byte that can never appear in UTF-8
		"{\"k\":\"v\xed\xa0\x80\"}", // surrogate half inside JSON
	} {
		got, err := tok.Encode(text)
		if err != nil {
			t.Errorf("Encode(%q): %v", text, err)
			continue
		}
		covered, prevStart := 0, 0
		for j, tk := range got {
			if tk.Start < prevStart {
				t.Errorf("%q token %d starts at %d, before the previous token's %d", text, j, tk.Start, prevStart)
			}
			if tk.Start > covered {
				t.Errorf("%q token %d starts at %d, leaving bytes [%d,%d) uncovered", text, j, tk.Start, covered, tk.Start)
			}
			if tk.End <= tk.Start || tk.End > len(text) {
				t.Errorf("%q token %d span [%d,%d) is out of range for %d bytes", text, j, tk.Start, tk.End, len(text))
			}
			if !charAligned(text, tk.Start) || !charAligned(text, tk.End) {
				t.Errorf("%q token %d span [%d,%d) does not align to a character boundary", text, j, tk.Start, tk.End)
			}
			prevStart = tk.Start
			if tk.End > covered {
				covered = tk.End
			}
		}
		if covered != len(text) {
			t.Errorf("%q: spans cover %d bytes, want %d", text, covered, len(text))
		}
	}
}
